// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-live-channels.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-live-channels.ts
var list_live_channels_default = defineTool({
  name: "list_live_channels",
  title: "List live channels",
  description: "List church channels that are currently broadcasting live.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("channels").select("id, name, description, is_live, current_viewers, live_started_at").eq("is_live", true).eq("is_approved", true).eq("is_suspended", false).order("current_viewers", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { channels: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-sermons.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var search_sermons_default = defineTool2({
  name: "search_sermons",
  title: "Search sermons",
  description: "Search sermon videos by keyword in title, preacher, or description.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to search for."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("sermons").select("id, title, preacher, category, sermon_date, description, channel_id, view_count").eq("is_hidden", false).or(`title.ilike.%${escaped}%,preacher.ilike.%${escaped}%,description.ilike.%${escaped}%`).order("sermon_date", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sermons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-sermon.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_sermon_default = defineTool3({
  name: "get_sermon",
  title: "Get sermon details",
  description: "Fetch full details for one sermon by its ID.",
  inputSchema: { sermon_id: z2.string().uuid().describe("Sermon UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sermon_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sermons").select("id, title, preacher, category, sermon_date, description, duration, video_url, thumbnail_url, view_count, channel_id").eq("id", sermon_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Sermon not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { sermon: data }
    };
  }
});

// src/lib/mcp/tools/list-my-notes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_notes_default = defineTool4({
  name: "list_my_sermon_notes",
  title: "List my sermon notes",
  description: "List the signed-in user's sermon notes, optionally filtered by sermon.",
  inputSchema: {
    sermon_id: z3.string().uuid().optional().describe("Only return notes for this sermon.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sermon_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("sermon_notes").select("id, sermon_id, content, image_url, created_at, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(50);
    if (sermon_id) query = query.eq("sermon_id", sermon_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-sermon-note.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var save_sermon_note_default = defineTool5({
  name: "save_sermon_note",
  title: "Save sermon note",
  description: "Create or update the signed-in user's note for a sermon.",
  inputSchema: {
    sermon_id: z4.string().uuid().describe("Sermon UUID the note belongs to."),
    content: z4.string().min(1).describe("Note text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ sermon_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: existing, error: findError } = await supabase.from("sermon_notes").select("id").eq("user_id", userId).eq("sermon_id", sermon_id).maybeSingle();
    if (findError) return { content: [{ type: "text", text: findError.message }], isError: true };
    const { data, error } = existing ? await supabase.from("sermon_notes").update({ content, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", existing.id).select() : await supabase.from("sermon_notes").insert({ user_id: userId, sermon_id, content }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { note: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nhdopijdmrowknwqouxw";
var mcp_default = defineMcp({
  name: "live-word-stream",
  title: "Live Word Stream",
  version: "0.1.0",
  instructions: "Tools for Live Word Stream, a church sermon streaming platform. Use `list_live_channels` for current live broadcasts, `search_sermons` / `get_sermon` to browse sermon videos, and `list_my_sermon_notes` / `save_sermon_note` for the signed-in user's personal sermon notes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_live_channels_default,
    search_sermons_default,
    get_sermon_default,
    list_my_notes_default,
    save_sermon_note_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
